spring.application.name=Imobliaria

spring.datasource.url=jdbc:postgresql://localhost:5432/imobiliaria
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=X7bAcAY7IvF42Ewt+X7tIUJZsjXLjMAGuqYRxDGyqHCAVUibfsV2R/cwV7zGtI1H7Ukkobcx9F3Ium5lGt8IQw==
jwt.expiration=86400000

admin.username=admin
admin.password=admin123

upload.dir=uploads/

server.port=8080
